import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

interface DutchVerb {
  number: number;
  english: string;
  dutch: string;
  conjugation: string;
  sentence: string;
}

@Component({
  selector: 'app-dutch-verbs',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './dutch-verbs.component.html',
  styleUrl: './dutch-verbs.component.css',
})
export class DutchVerbsComponent {
  searchQuery = '';

  verbs: DutchVerb[] = [
    {
      number: 1,
      english: 'To finish',
      dutch: 'Afronden',
      conjugation: 'ik rond af, jij rondt af, hij rondt af, wij ronden af',
      sentence: 'Ik moet dit ticket vandaag afronden.',
    },
    {
      number: 2,
      english: 'To check',
      dutch: 'Controleren',
      conjugation: 'ik controleer, jij controleert, hij controleert, wij controleren',
      sentence: 'Kun je dit even controleren?',
    },
    {
      number: 3,
      english: 'To solve / fix',
      dutch: 'Oplossen',
      conjugation: 'ik los op, jij lost op, hij lost op, wij lossen op',
      sentence: 'We moeten dit probleem oplossen.',
    },
    {
      number: 4,
      english: 'To discuss',
      dutch: 'Bespreken',
      conjugation: 'ik bespreek, jij bespreekt, hij bespreekt, wij bespreken',
      sentence: 'We moeten dit bespreken in de meeting.',
    },
    {
      number: 5,
      english: 'To plan',
      dutch: 'Plannen',
      conjugation: 'ik plan, jij plant, hij plant, wij plannen',
      sentence: 'We plannen de sprint voor twee weken.',
    },
    {
      number: 6,
      english: 'To deliver',
      dutch: 'Opleveren',
      conjugation: 'ik lever op, jij levert op, hij levert op, wij leveren op',
      sentence: 'We moeten dit aan het einde van de sprint opleveren.',
    },
    {
      number: 7,
      english: 'To deploy',
      dutch: 'Uitrollen',
      conjugation: 'ik rol uit, jij rolt uit, hij rolt uit, wij rollen uit',
      sentence: 'We rollen de applicatie uit naar productie.',
    },
    {
      number: 8,
      english: 'To review',
      dutch: 'Beoordelen',
      conjugation: 'ik beoordeel, jij beoordeelt, hij beoordeelt, wij beoordelen',
      sentence: 'Kun jij mijn code beoordelen?',
    },
    {
      number: 9,
      english: 'To implement',
      dutch: 'Implementeren',
      conjugation: 'ik implementeer, jij implementeert, hij implementeert, wij implementeren',
      sentence: 'Ik ga de nieuwe feature implementeren.',
    },
    {
      number: 10,
      english: 'To change',
      dutch: 'Wijzigen',
      conjugation: 'ik wijzig, jij wijzigt, hij wijzigt, wij wijzigen',
      sentence: 'We moeten de aanpak wijzigen.',
    },
    {
      number: 11,
      english: 'To update',
      dutch: 'Bijwerken',
      conjugation: 'ik werk bij, jij werkt bij, hij werkt bij, wij werken bij',
      sentence: 'Kun je de documentatie bijwerken?',
    },
    {
      number: 12,
      english: 'To confirm',
      dutch: 'Bevestigen',
      conjugation: 'ik bevestig, jij bevestigt, hij bevestigt, wij bevestigen',
      sentence: 'Kun je bevestigen dat dit correct is?',
    },
    {
      number: 13,
      english: 'To receive',
      dutch: 'Ontvangen',
      conjugation: 'ik ontvang, jij ontvangt, hij ontvangt, wij ontvangen',
      sentence: 'Heb je mijn e-mail ontvangen?',
    },
    {
      number: 14,
      english: 'To save',
      dutch: 'Opslaan',
      conjugation: 'ik sla op, jij slaat op, hij slaat op, wij slaan op',
      sentence: 'Vergeet niet je werk op te slaan.',
    },
    {
      number: 15,
      english: 'To delete',
      dutch: 'Verwijderen',
      conjugation: 'ik verwijder, jij verwijdert, hij verwijdert, wij verwijderen',
      sentence: 'Ik ga de oude branch verwijderen.',
    },
    {
      number: 16,
      english: 'To create',
      dutch: 'Aanmaken',
      conjugation: 'ik maak aan, jij maakt aan, hij maakt aan, wij maken aan',
      sentence: 'Ik maak een nieuwe branch aan.',
    },
    {
      number: 17,
      english: 'To run',
      dutch: 'Uitvoeren',
      conjugation: 'ik voer uit, jij voert uit, hij voert uit, wij voeren uit',
      sentence: 'Ik voer de tests uit.',
    },
    {
      number: 18,
      english: 'To install',
      dutch: 'Installeren',
      conjugation: 'ik installeer, jij installeert, hij installeert, wij installeren',
      sentence: 'Kun je de dependencies installeren?',
    },
    {
      number: 19,
      english: 'To configure',
      dutch: 'Configureren',
      conjugation: 'ik configureer, jij configureert, hij configureert, wij configureren',
      sentence: 'Ik moet de omgeving configureren.',
    },
    {
      number: 20,
      english: 'To connect',
      dutch: 'Verbinden',
      conjugation: 'ik verbind, jij verbindt, hij verbindt, wij verbinden',
      sentence: 'Ik kan niet verbinden met de database.',
    },
    {
      number: 21,
      english: 'To merge',
      dutch: 'Samenvoegen',
      conjugation: 'ik voeg samen, jij voegt samen, hij voegt samen, wij voegen samen',
      sentence: 'Ik ga de branch samenvoegen.',
    },
    {
      number: 22,
      english: 'To push',
      dutch: 'Pushen',
      conjugation: 'ik push, jij pusht, hij pusht, wij pushen',
      sentence: 'Ik ga de code pushen naar de repository.',
    },
    {
      number: 23,
      english: 'To pull',
      dutch: 'Pullen',
      conjugation: 'ik pull, jij pullt, hij pullt, wij pullen',
      sentence: 'Vergeet niet te pullen voor je begint.',
    },
    {
      number: 24,
      english: 'To estimate',
      dutch: 'Inschatten',
      conjugation: 'ik schat in, jij schat in, hij schat in, wij schatten in',
      sentence: 'Hoe schat jij de tijd in voor dit ticket?',
    },
    {
      number: 25,
      english: 'To refactor',
      dutch: 'Refactoren',
      conjugation: 'ik refactor, jij refactort, hij refactort, wij refactoren',
      sentence: 'We moeten deze code refactoren.',
    },
    {
      number: 26,
      english: 'To investigate',
      dutch: 'Onderzoeken',
      conjugation: 'ik onderzoek, jij onderzoekt, hij onderzoekt, wij onderzoeken',
      sentence: 'Ik ga de bug onderzoeken.',
    },
    {
      number: 27,
      english: 'To improve',
      dutch: 'Verbeteren',
      conjugation: 'ik verbeter, jij verbetert, hij verbetert, wij verbeteren',
      sentence: 'We kunnen de performance verbeteren.',
    },
    {
      number: 28,
      english: 'To add',
      dutch: 'Toevoegen',
      conjugation: 'ik voeg toe, jij voegt toe, hij voegt toe, wij voegen toe',
      sentence: 'Ik voeg een nieuwe endpoint toe.',
    },
    {
      number: 29,
      english: 'To remove',
      dutch: 'Verwijderen',
      conjugation: 'ik verwijder, jij verwijdert, hij verwijdert, wij verwijderen',
      sentence: 'We moeten de oude code verwijderen.',
    },
    {
      number: 30,
      english: 'To approve',
      dutch: 'Goedkeuren',
      conjugation: 'ik keur goed, jij keurt goed, hij keurt goed, wij keuren goed',
      sentence: 'Kun je mijn PR goedkeuren?',
    },
    {
      number: 31,
      english: 'To reject',
      dutch: 'Afwijzen',
      conjugation: 'ik wijs af, jij wijst af, hij wijst af, wij wijzen af',
      sentence: 'De PR werd afgewezen vanwege een fout.',
    },
    {
      number: 32,
      english: 'To present',
      dutch: 'Presenteren',
      conjugation: 'ik presenteer, jij presenteert, hij presenteert, wij presenteren',
      sentence: 'Ik ga de resultaten presenteren.',
    },
    {
      number: 33,
      english: 'To attend',
      dutch: 'Bijwonen',
      conjugation: 'ik woon bij, jij woont bij, hij woont bij, wij wonen bij',
      sentence: 'Ik woon de standup bij.',
    },
    {
      number: 34,
      english: 'To schedule',
      dutch: 'Inplannen',
      conjugation: 'ik plan in, jij plant in, hij plant in, wij plannen in',
      sentence: 'Kun je de meeting inplannen?',
    },
    {
      number: 35,
      english: 'To postpone',
      dutch: 'Uitstellen',
      conjugation: 'ik stel uit, jij stelt uit, hij stelt uit, wij stellen uit',
      sentence: 'We moeten de deadline uitstellen.',
    },
    {
      number: 36,
      english: 'To report',
      dutch: 'Rapporteren',
      conjugation: 'ik rapporteer, jij rapporteert, hij rapporteert, wij rapporteren',
      sentence: 'Ik ga de voortgang rapporteren.',
    },
    {
      number: 37,
      english: 'To block',
      dutch: 'Blokkeren',
      conjugation: 'ik blokkeer, jij blokkeert, hij blokkeert, wij blokkeren',
      sentence: 'Dit ticket blokkeert mijn werk.',
    },
    {
      number: 38,
      english: 'To depend on',
      dutch: 'Afhangen van',
      conjugation: 'het hangt af van',
      sentence: 'Dit hangt af van de backend implementatie.',
    },
    {
      number: 39,
      english: 'To integrate',
      dutch: 'Integreren',
      conjugation: 'ik integreer, jij integreert, hij integreert, wij integreren',
      sentence: 'We moeten de API integreren.',
    },
    {
      number: 40,
      english: 'To automate',
      dutch: 'Automatiseren',
      conjugation: 'ik automatiseer, jij automatiseert, hij automatiseert, wij automatiseren',
      sentence: 'We willen het testproces automatiseren.',
    },
    {
      number: 41,
      english: 'To monitor',
      dutch: 'Monitoren',
      conjugation: 'ik monitor, jij monitort, hij monitort, wij monitoren',
      sentence: 'We monitoren de applicatie in productie.',
    },
    {
      number: 42,
      english: 'To log',
      dutch: 'Loggen',
      conjugation: 'ik log, jij logt, hij logt, wij loggen',
      sentence: 'De applicatie logt alle fouten.',
    },
    {
      number: 43,
      english: 'To debug',
      dutch: 'Debuggen',
      conjugation: 'ik debug, jij debugt, hij debugt, wij debuggen',
      sentence: 'Ik ben aan het debuggen.',
    },
    {
      number: 44,
      english: 'To optimize',
      dutch: 'Optimaliseren',
      conjugation: 'ik optimaliseer, jij optimaliseert, hij optimaliseert, wij optimaliseren',
      sentence: 'We moeten de query optimaliseren.',
    },
    {
      number: 45,
      english: 'To migrate',
      dutch: 'Migreren',
      conjugation: 'ik migreer, jij migreert, hij migreert, wij migreren',
      sentence: 'We migreren de database naar de cloud.',
    },
    {
      number: 46,
      english: 'To store',
      dutch: 'Opslaan',
      conjugation: 'ik sla op, jij slaat op, hij slaat op, wij slaan op',
      sentence: 'De gegevens worden opgeslagen in de database.',
    },
    {
      number: 47,
      english: 'To load',
      dutch: 'Laden',
      conjugation: 'ik laad, jij laadt, hij laadt, wij laden',
      sentence: 'De pagina laadt te langzaam.',
    },
    {
      number: 48,
      english: 'To upload',
      dutch: 'Uploaden',
      conjugation: 'ik upload, jij uploadt, hij uploadt, wij uploaden',
      sentence: 'Ik upload het bestand naar de server.',
    },
    {
      number: 49,
      english: 'To download',
      dutch: 'Downloaden',
      conjugation: 'ik download, jij downloadt, hij downloadt, wij downloaden',
      sentence: 'Kun je het bestand downloaden?',
    },
    {
      number: 50,
      english: 'To access',
      dutch: 'Toegang hebben',
      conjugation: 'ik heb toegang, jij hebt toegang',
      sentence: 'Ik heb geen toegang tot de server.',
    },
    {
      number: 51,
      english: 'To agree',
      dutch: 'Akkoord gaan',
      conjugation: 'ik ga akkoord, jij gaat akkoord',
      sentence: 'Ik ga akkoord met het voorstel.',
    },
    {
      number: 52,
      english: 'To disagree',
      dutch: 'Het er niet mee eens zijn',
      conjugation: 'ik ben het er niet mee eens',
      sentence: 'Ik ben het er niet mee eens — ik denk dat er een betere aanpak is.',
    },
    {
      number: 53,
      english: 'To suggest',
      dutch: 'Voorstellen',
      conjugation: 'ik stel voor, jij stelt voor, hij stelt voor, wij stellen voor',
      sentence: 'Ik stel voor om dit anders aan te pakken.',
    },
    {
      number: 54,
      english: 'To respond',
      dutch: 'Reageren',
      conjugation: 'ik reageer, jij reageert, hij reageert, wij reageren',
      sentence: 'Ik reageer zo snel mogelijk op je vraag.',
    },
    {
      number: 55,
      english: 'To handle',
      dutch: 'Afhandelen',
      conjugation: 'ik handel af, jij handelt af, hij handelt af, wij handelen af',
      sentence: 'Ik handel de foutmelding af.',
    },
    {
      number: 56,
      english: 'To continue',
      dutch: 'Doorgaan',
      conjugation: 'ik ga door, jij gaat door, hij gaat door, wij gaan door',
      sentence: 'Laten we doorgaan met de volgende taak.',
    },
    {
      number: 57,
      english: 'To succeed',
      dutch: 'Slagen',
      conjugation: 'ik slaag, jij slaagt, hij slaagt, wij slagen',
      sentence: 'Ik wil slagen in mijn nieuwe rol.',
    },
    {
      number: 58,
      english: 'To manage',
      dutch: 'Beheren',
      conjugation: 'ik beheer, jij beheert, hij beheert, wij beheren',
      sentence: 'Ik beheer de configuratie van de server.',
    },
    {
      number: 59,
      english: 'To assign',
      dutch: 'Toewijzen',
      conjugation: 'ik wijs toe, jij wijst toe, hij wijst toe, wij wijzen toe',
      sentence: 'Kun je dit ticket aan mij toewijzen?',
    },
    {
      number: 60,
      english: 'To copy',
      dutch: 'Kopiëren',
      conjugation: 'ik kopieer, jij kopieert, hij kopieert, wij kopiëren',
      sentence: 'Ik kopieer de configuratie naar de nieuwe omgeving.',
    },
    {
      number: 61,
      english: 'To paste',
      dutch: 'Plakken',
      conjugation: 'ik plak, jij plakt, hij plakt, wij plakken',
      sentence: 'Kun je de foutmelding hier plakken?',
    },
    {
      number: 62,
      english: 'To restart',
      dutch: 'Herstarten',
      conjugation: 'ik herstart, jij herstart, hij herstart, wij herstarten',
      sentence: 'Ik moet de server herstarten.',
    },
    {
      number: 63,
      english: 'To track',
      dutch: 'Bijhouden',
      conjugation: 'ik houd bij, jij houdt bij, hij houdt bij, wij houden bij',
      sentence: 'We houden de voortgang bij in Jira.',
    },
    {
      number: 64,
      english: 'To maintain',
      dutch: 'Onderhouden',
      conjugation: 'ik onderhoud, jij onderhoudt, hij onderhoudt, wij onderhouden',
      sentence: 'We onderhouden de legacy applicatie.',
    },
    {
      number: 65,
      english: 'To extend',
      dutch: 'Uitbreiden',
      conjugation: 'ik breid uit, jij breidt uit, hij breidt uit, wij breiden uit',
      sentence: 'We willen de functionaliteit uitbreiden.',
    },
    {
      number: 66,
      english: 'To reduce',
      dutch: 'Verminderen',
      conjugation: 'ik verminder, jij vermindert, hij vermindert, wij verminderen',
      sentence: 'We willen de laadtijd verminderen.',
    },
    {
      number: 67,
      english: 'To replace',
      dutch: 'Vervangen',
      conjugation: 'ik vervang, jij vervangt, hij vervangt, wij vervangen',
      sentence: 'We gaan de oude library vervangen.',
    },
    {
      number: 68,
      english: 'To compare',
      dutch: 'Vergelijken',
      conjugation: 'ik vergelijk, jij vergelijkt, hij vergelijkt, wij vergelijken',
      sentence: 'Laten we de twee aanpakken vergelijken.',
    },
    {
      number: 69,
      english: 'To validate',
      dutch: 'Valideren',
      conjugation: 'ik valideer, jij valideert, hij valideert, wij valideren',
      sentence: 'We moeten de invoer valideren.',
    },
    {
      number: 70,
      english: 'To generate',
      dutch: 'Genereren',
      conjugation: 'ik genereer, jij genereert, hij genereert, wij genereren',
      sentence: 'De tool genereert automatisch de code.',
    },
    {
      number: 71,
      english: 'To parse',
      dutch: 'Verwerken',
      conjugation: 'ik verwerk, jij verwerkt, hij verwerkt, wij verwerken',
      sentence: 'We verwerken de JSON respons van de API.',
    },
    {
      number: 72,
      english: 'To format',
      dutch: 'Opmaken',
      conjugation: 'ik maak op, jij maakt op, hij maakt op, wij maken op',
      sentence: 'Vergeet niet de code op te maken met Prettier.',
    },
    {
      number: 73,
      english: 'To prioritize',
      dutch: 'Prioriteren',
      conjugation: 'ik prioriteer, jij prioriteert, hij prioriteert, wij prioriteren',
      sentence: 'We moeten de taken prioriteren voor de sprint.',
    },
    {
      number: 74,
      english: 'To document',
      dutch: 'Documenteren',
      conjugation: 'ik documenteer, jij documenteert, hij documenteert, wij documenteren',
      sentence: 'Vergeet niet de nieuwe feature te documenteren.',
    },
    {
      number: 75,
      english: 'To split',
      dutch: 'Opsplitsen',
      conjugation: 'ik splits op, jij splitst op, hij splitst op, wij splitsen op',
      sentence: 'We moeten dit grote ticket opsplitsen.',
    },
    {
      number: 76,
      english: 'To escalate',
      dutch: 'Escaleren',
      conjugation: 'ik escaleer, jij escaleert, hij escaleert, wij escaleren',
      sentence: 'Dit probleem moeten we escaleren naar de teamleider.',
    },
    {
      number: 77,
      english: 'To clarify',
      dutch: 'Verduidelijken',
      conjugation: 'ik verduidelijk, jij verduidelijkt, hij verduidelijkt, wij verduidelijken',
      sentence: 'Kun je de requirements verduidelijken?',
    },
    {
      number: 78,
      english: 'To mock',
      dutch: 'Nabootsen',
      conjugation: 'ik boots na, jij bootst na, hij bootst na, wij bootsen na',
      sentence: 'We bootsen de API na in de tests.',
    },
    {
      number: 79,
      english: 'To cache',
      dutch: 'Cachen',
      conjugation: 'ik cache, jij cachet, hij cachet, wij cachen',
      sentence: 'De applicatie cachet de resultaten voor betere prestaties.',
    },
    {
      number: 80,
      english: 'To encrypt',
      dutch: 'Versleutelen',
      conjugation: 'ik versleutel, jij versleutelt, hij versleutelt, wij versleutelen',
      sentence: 'We versleutelen alle wachtwoorden in de database.',
    },
    {
      number: 81,
      english: 'To authenticate',
      dutch: 'Authenticeren',
      conjugation: 'ik authenticeer, jij authenticeert, hij authenticeert, wij authenticeren',
      sentence: 'De gebruiker moet zich authenticeren via Azure AD.',
    },
    {
      number: 82,
      english: 'To authorize',
      dutch: 'Autoriseren',
      conjugation: 'ik autoriseer, jij autoriseert, hij autoriseert, wij autoriseren',
      sentence: 'Spring Security autoriseert de API requests.',
    },
    {
      number: 83,
      english: 'To scale',
      dutch: 'Opschalen',
      conjugation: 'ik schaal op, jij schaalt op, hij schaalt op, wij schalen op',
      sentence: 'We moeten de applicatie opschalen in Azure.',
    },
    {
      number: 84,
      english: 'To synchronize',
      dutch: 'Synchroniseren',
      conjugation: 'ik synchroniseer, jij synchroniseert, hij synchroniseert, wij synchroniseren',
      sentence: 'De data wordt gesynchroniseerd met de backend.',
    },
    {
      number: 85,
      english: 'To backup',
      dutch: 'Back-uppen',
      conjugation: 'ik back-up, jij back-upt, hij back-upt, wij back-uppen',
      sentence: 'We back-uppen de database elke nacht.',
    },
    {
      number: 86,
      english: 'To refine',
      dutch: 'Verfijnen',
      conjugation: 'ik verfijn, jij verfijnt, hij verfijnt, wij verfijnen',
      sentence: 'We verfijnen de user stories tijdens de refinement.',
    },
    {
      number: 87,
      english: 'To expose',
      dutch: 'Blootstellen',
      conjugation: 'ik stel bloot, jij stelt bloot, hij stelt bloot, wij stellen bloot',
      sentence: 'We mogen geen gevoelige data blootstellen.',
    },
    {
      number: 88,
      english: 'To commit to',
      dutch: 'Zich committeren aan',
      conjugation: 'ik committeer me aan',
      sentence: 'We committeren ons aan de sprintdoelen.',
    },
    {
      number: 89,
      english: 'To prototype',
      dutch: 'Prototypen',
      conjugation: 'ik prototypeer, jij prototypt, hij prototypt, wij prototypen',
      sentence: 'Ik ga eerst een prototype bouwen.',
    },
    {
      number: 90,
      english: 'To clarify again',
      dutch: 'Nader toelichten',
      conjugation: 'ik licht nader toe, jij licht nader toe, wij lichten nader toe',
      sentence: 'Kun je dit nader toelichten?',
    },
    {
      number: 91,
      english: 'To test again',
      dutch: 'Hertesten',
      conjugation: 'ik hertest, jij hertest, hij hertest, wij hertesten',
      sentence: 'We moeten de fix hertesten na de deployment.',
    },
    {
      number: 92,
      english: 'To transfer',
      dutch: 'Overdragen',
      conjugation: 'ik draag over, jij draagt over, hij draagt over, wij dragen over',
      sentence: 'Ik draag het ticket over aan mijn collega.',
    },
    {
      number: 93,
      english: 'To notify',
      dutch: 'Informeren',
      conjugation: 'ik informeer, jij informeert, hij informeert, wij informeren',
      sentence: 'Kun je het team informeren over de wijziging?',
    },
    {
      number: 94,
      english: 'To convert',
      dutch: 'Omzetten',
      conjugation: 'ik zet om, jij zet om, hij zet om, wij zetten om',
      sentence: 'We zetten de entity om naar een DTO.',
    },
    {
      number: 95,
      english: 'To override',
      dutch: 'Overschrijven',
      conjugation: 'ik overschrijf, jij overschrijft, hij overschrijft, wij overschrijven',
      sentence: 'Ik overschrijf de standaard configuratie.',
    },
    {
      number: 96,
      english: 'To initialize',
      dutch: 'Initialiseren',
      conjugation: 'ik initialiseer, jij initialiseert, hij initialiseert, wij initialiseren',
      sentence: 'We initialiseren de database bij de eerste keer opstarten.',
    },
    {
      number: 97,
      english: 'To inject',
      dutch: 'Injecteren',
      conjugation: 'ik injecteer, jij injecteert, hij injecteert, wij injecteren',
      sentence: 'Spring Boot injecteert de dependencies automatisch.',
    },
    {
      number: 98,
      english: 'To serialize',
      dutch: 'Serialiseren',
      conjugation: 'ik serialiseer, jij serialiseert, hij serialiseert, wij serialiseren',
      sentence: 'Jackson serialiseert het object naar JSON.',
    },
    {
      number: 99,
      english: 'To deserialize',
      dutch: 'Deserialiseren',
      conjugation: 'ik deserialiseer, jij deserialiseert, hij deserialiseert, wij deserialiseren',
      sentence: 'We deserialiseren de JSON respons naar een Java object.',
    },
    {
      number: 100,
      english: 'To inherit',
      dutch: 'Overerven',
      conjugation: 'ik erf over, jij erft over, hij erft over, wij erven over',
      sentence: 'Deze klasse erft over van de basisklasse.',
    },
  ];

  get filteredVerbs(): DutchVerb[] {
    if (!this.searchQuery.trim()) return this.verbs;
    const q = this.searchQuery.toLowerCase();
    return this.verbs.filter(
      (v) =>
        v.english.toLowerCase().includes(q) ||
        v.dutch.toLowerCase().includes(q) ||
        v.conjugation.toLowerCase().includes(q) ||
        v.sentence.toLowerCase().includes(q)
    );
  }
}
