import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

interface DutchVerb {
  number: number;
  english: string;
  dutch: string;
  conjugation: string;
  sentence: string;
}

@Component({
  selector: 'app-dutch-verbs',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './dutch-verbs.component.html',
  styleUrl: './dutch-verbs.component.css',
})
export class DutchVerbsComponent {
  searchQuery = '';

  verbs: DutchVerb[] = [
    {
      number: 1,
      english: 'To be',
      dutch: 'Zijn',
      conjugation: 'ik ben, jij bent, hij is, wij zijn',
      sentence: 'Ik ben een developer.',
    },
    {
      number: 2,
      english: 'To have',
      dutch: 'Hebben',
      conjugation: 'ik heb, jij hebt, hij heeft, wij hebben',
      sentence: 'Ik heb een vraag.',
    },
    {
      number: 3,
      english: 'To do / make',
      dutch: 'Doen',
      conjugation: 'ik doe, jij doet, hij doet, wij doen',
      sentence: 'Wat doe jij vandaag?',
    },
    {
      number: 4,
      english: 'To go',
      dutch: 'Gaan',
      conjugation: 'ik ga, jij gaat, hij gaat, wij gaan',
      sentence: 'Ik ga naar kantoor.',
    },
    {
      number: 5,
      english: 'To come',
      dutch: 'Komen',
      conjugation: 'ik kom, jij komt, hij komt, wij komen',
      sentence: 'Kun je naar de meeting komen?',
    },
    {
      number: 6,
      english: 'To say / tell',
      dutch: 'Zeggen',
      conjugation: 'ik zeg, jij zegt, hij zegt, wij zeggen',
      sentence: 'Wat wil je zeggen?',
    },
    {
      number: 7,
      english: 'To see',
      dutch: 'Zien',
      conjugation: 'ik zie, jij ziet, hij ziet, wij zien',
      sentence: 'Ik zie het probleem niet.',
    },
    {
      number: 8,
      english: 'To know',
      dutch: 'Weten',
      conjugation: 'ik weet, jij weet, hij weet, wij weten',
      sentence: 'Weet jij wat het probleem is?',
    },
    {
      number: 9,
      english: 'To think',
      dutch: 'Denken',
      conjugation: 'ik denk, jij denkt, hij denkt, wij denken',
      sentence: 'Ik denk dat dit de oplossing is.',
    },
    {
      number: 10,
      english: 'To want',
      dutch: 'Willen',
      conjugation: 'ik wil, jij wilt, hij wil, wij willen',
      sentence: 'Ik wil dit ticket oppakken.',
    },
    {
      number: 11,
      english: 'To can / be able',
      dutch: 'Kunnen',
      conjugation: 'ik kan, jij kunt, hij kan, wij kunnen',
      sentence: 'Kun je me helpen met dit probleem?',
    },
    {
      number: 12,
      english: 'To must / have to',
      dutch: 'Moeten',
      conjugation: 'ik moet, jij moet, hij moet, wij moeten',
      sentence: 'Ik moet dit ticket vandaag afronden.',
    },
    {
      number: 13,
      english: 'To may / might',
      dutch: 'Mogen',
      conjugation: 'ik mag, jij mag, hij mag, wij mogen',
      sentence: 'Mag ik een vraag stellen?',
    },
    {
      number: 14,
      english: 'To shall / will',
      dutch: 'Zullen',
      conjugation: 'ik zal, jij zult, hij zal, wij zullen',
      sentence: 'Ik zal het morgen oplossen.',
    },
    {
      number: 15,
      english: 'To work',
      dutch: 'Werken',
      conjugation: 'ik werk, jij werkt, hij werkt, wij werken',
      sentence: 'Ik werk aan de nieuwe feature.',
    },
    {
      number: 16,
      english: 'To look / watch',
      dutch: 'Kijken',
      conjugation: 'ik kijk, jij kijkt, hij kijkt, wij kijken',
      sentence: 'Kun je even kijken naar mijn code?',
    },
    {
      number: 17,
      english: 'To give',
      dutch: 'Geven',
      conjugation: 'ik geef, jij geeft, hij geeft, wij geven',
      sentence: 'Kun je me feedback geven?',
    },
    {
      number: 18,
      english: 'To take',
      dutch: 'Nemen',
      conjugation: 'ik neem, jij neemt, hij neemt, wij nemen',
      sentence: 'Ik neem dit ticket op.',
    },
    {
      number: 19,
      english: 'To find',
      dutch: 'Vinden',
      conjugation: 'ik vind, jij vindt, hij vindt, wij vinden',
      sentence: 'Ik vind dit een goed idee.',
    },
    {
      number: 20,
      english: 'To ask',
      dutch: 'Vragen',
      conjugation: 'ik vraag, jij vraagt, hij vraagt, wij vragen',
      sentence: 'Ik wil iets vragen over de architectuur.',
    },
    {
      number: 21,
      english: 'To put / place',
      dutch: 'Zetten',
      conjugation: 'ik zet, jij zet, hij zet, wij zetten',
      sentence: 'Ik zet het ticket op in progress.',
    },
    {
      number: 22,
      english: 'To stand',
      dutch: 'Staan',
      conjugation: 'ik sta, jij staat, hij staat, wij staan',
      sentence: 'Er staat een fout in de code.',
    },
    {
      number: 23,
      english: 'To leave / let',
      dutch: 'Laten',
      conjugation: 'ik laat, jij laat, hij laat, wij laten',
      sentence: 'Laat me even kijken.',
    },
    {
      number: 24,
      english: 'To seem / appear',
      dutch: 'Lijken',
      conjugation: 'ik lijk, jij lijkt, hij lijkt, wij lijken',
      sentence: 'Het lijkt erop dat er een bug is.',
    },
    {
      number: 25,
      english: 'To become',
      dutch: 'Worden',
      conjugation: 'ik word, jij wordt, hij wordt, wij worden',
      sentence: 'Dit wordt een grote taak.',
    },
    {
      number: 26,
      english: 'To help',
      dutch: 'Helpen',
      conjugation: 'ik help, jij helpt, hij helpt, wij helpen',
      sentence: 'Kun je me helpen met de configuratie?',
    },
    {
      number: 27,
      english: 'To try',
      dutch: 'Proberen',
      conjugation: 'ik probeer, jij probeert, hij probeert, wij proberen',
      sentence: 'Ik probeer het probleem op te lossen.',
    },
    {
      number: 28,
      english: 'To understand',
      dutch: 'Begrijpen',
      conjugation: 'ik begrijp, jij begrijpt, hij begrijpt, wij begrijpen',
      sentence: 'Ik begrijp de vereisten niet helemaal.',
    },
    {
      number: 29,
      english: 'To explain',
      dutch: 'Uitleggen',
      conjugation: 'ik leg uit, jij legt uit, hij legt uit, wij leggen uit',
      sentence: 'Kun je uitleggen hoe dit werkt?',
    },
    {
      number: 30,
      english: 'To start / begin',
      dutch: 'Beginnen',
      conjugation: 'ik begin, jij begint, hij begint, wij beginnen',
      sentence: 'Wanneer beginnen we met de sprint?',
    },
    {
      number: 31,
      english: 'To finish',
      dutch: 'Afronden',
      conjugation: 'ik rond af, jij rondt af, hij rondt af, wij ronden af',
      sentence: 'Ik moet dit ticket vandaag afronden.',
    },
    {
      number: 32,
      english: 'To check',
      dutch: 'Controleren',
      conjugation: 'ik controleer, jij controleert, hij controleert, wij controleren',
      sentence: 'Kun je dit even controleren?',
    },
    {
      number: 33,
      english: 'To solve / fix',
      dutch: 'Oplossen',
      conjugation: 'ik los op, jij lost op, hij lost op, wij lossen op',
      sentence: 'We moeten dit probleem oplossen.',
    },
    {
      number: 34,
      english: 'To discuss',
      dutch: 'Bespreken',
      conjugation: 'ik bespreek, jij bespreekt, hij bespreekt, wij bespreken',
      sentence: 'We moeten dit bespreken in de meeting.',
    },
    {
      number: 35,
      english: 'To plan',
      dutch: 'Plannen',
      conjugation: 'ik plan, jij plant, hij plant, wij plannen',
      sentence: 'We plannen de sprint voor twee weken.',
    },
    {
      number: 36,
      english: 'To deliver',
      dutch: 'Opleveren',
      conjugation: 'ik lever op, jij levert op, hij levert op, wij leveren op',
      sentence: 'We moeten dit aan het einde van de sprint opleveren.',
    },
    {
      number: 37,
      english: 'To test',
      dutch: 'Testen',
      conjugation: 'ik test, jij test, hij test, wij testen',
      sentence: 'Heb je de nieuwe functie al getest?',
    },
    {
      number: 38,
      english: 'To deploy',
      dutch: 'Uitrollen',
      conjugation: 'ik rol uit, jij rolt uit, hij rolt uit, wij rollen uit',
      sentence: 'We rollen de applicatie uit naar productie.',
    },
    {
      number: 39,
      english: 'To review',
      dutch: 'Beoordelen',
      conjugation: 'ik beoordeel, jij beoordeelt, hij beoordeelt, wij beoordelen',
      sentence: 'Kun jij mijn code beoordelen?',
    },
    {
      number: 40,
      english: 'To implement',
      dutch: 'Implementeren',
      conjugation: 'ik implementeer, jij implementeert, hij implementeert, wij implementeren',
      sentence: 'Ik ga de nieuwe feature implementeren.',
    },
    {
      number: 41,
      english: 'To change',
      dutch: 'Wijzigen',
      conjugation: 'ik wijzig, jij wijzigt, hij wijzigt, wij wijzigen',
      sentence: 'We moeten de aanpak wijzigen.',
    },
    {
      number: 42,
      english: 'To update',
      dutch: 'Bijwerken',
      conjugation: 'ik werk bij, jij werkt bij, hij werkt bij, wij werken bij',
      sentence: 'Kun je de documentatie bijwerken?',
    },
    {
      number: 43,
      english: 'To confirm',
      dutch: 'Bevestigen',
      conjugation: 'ik bevestig, jij bevestigt, hij bevestigt, wij bevestigen',
      sentence: 'Kun je bevestigen dat dit correct is?',
    },
    {
      number: 44,
      english: 'To wait',
      dutch: 'Wachten',
      conjugation: 'ik wacht, jij wacht, hij wacht, wij wachten',
      sentence: 'Ik wacht op de goedkeuring van de PR.',
    },
    {
      number: 45,
      english: 'To read',
      dutch: 'Lezen',
      conjugation: 'ik lees, jij leest, hij leest, wij lezen',
      sentence: 'Heb je de documentatie al gelezen?',
    },
    {
      number: 46,
      english: 'To write',
      dutch: 'Schrijven',
      conjugation: 'ik schrijf, jij schrijft, hij schrijft, wij schrijven',
      sentence: 'Ik schrijf de unit tests.',
    },
    {
      number: 47,
      english: 'To send',
      dutch: 'Sturen',
      conjugation: 'ik stuur, jij stuurt, hij stuurt, wij sturen',
      sentence: 'Kun je de link sturen?',
    },
    {
      number: 48,
      english: 'To receive',
      dutch: 'Ontvangen',
      conjugation: 'ik ontvang, jij ontvangt, hij ontvangt, wij ontvangen',
      sentence: 'Heb je mijn e-mail ontvangen?',
    },
    {
      number: 49,
      english: 'To open',
      dutch: 'Openen',
      conjugation: 'ik open, jij opent, hij opent, wij openen',
      sentence: 'Kun je de applicatie openen?',
    },
    {
      number: 50,
      english: 'To close',
      dutch: 'Sluiten',
      conjugation: 'ik sluit, jij sluit, hij sluit, wij sluiten',
      sentence: 'Ik ga het ticket sluiten.',
    },
    {
      number: 51,
      english: 'To save',
      dutch: 'Opslaan',
      conjugation: 'ik sla op, jij slaat op, hij slaat op, wij slaan op',
      sentence: 'Vergeet niet je werk op te slaan.',
    },
    {
      number: 52,
      english: 'To delete',
      dutch: 'Verwijderen',
      conjugation: 'ik verwijder, jij verwijdert, hij verwijdert, wij verwijderen',
      sentence: 'Ik ga de oude branch verwijderen.',
    },
    {
      number: 53,
      english: 'To create',
      dutch: 'Aanmaken',
      conjugation: 'ik maak aan, jij maakt aan, hij maakt aan, wij maken aan',
      sentence: 'Ik maak een nieuwe branch aan.',
    },
    {
      number: 54,
      english: 'To run',
      dutch: 'Uitvoeren',
      conjugation: 'ik voer uit, jij voert uit, hij voert uit, wij voeren uit',
      sentence: 'Ik voer de tests uit.',
    },
    {
      number: 55,
      english: 'To install',
      dutch: 'Installeren',
      conjugation: 'ik installeer, jij installeert, hij installeert, wij installeren',
      sentence: 'Kun je de dependencies installeren?',
    },
    {
      number: 56,
      english: 'To configure',
      dutch: 'Configureren',
      conjugation: 'ik configureer, jij configureert, hij configureert, wij configureren',
      sentence: 'Ik moet de omgeving configureren.',
    },
    {
      number: 57,
      english: 'To connect',
      dutch: 'Verbinden',
      conjugation: 'ik verbind, jij verbindt, hij verbindt, wij verbinden',
      sentence: 'Ik kan niet verbinden met de database.',
    },
    {
      number: 58,
      english: 'To merge',
      dutch: 'Samenvoegen',
      conjugation: 'ik voeg samen, jij voegt samen, hij voegt samen, wij voegen samen',
      sentence: 'Ik ga de branch samenvoegen.',
    },
    {
      number: 59,
      english: 'To push',
      dutch: 'Pushen',
      conjugation: 'ik push, jij pusht, hij pusht, wij pushen',
      sentence: 'Ik ga de code pushen naar de repository.',
    },
    {
      number: 60,
      english: 'To pull',
      dutch: 'Pullen',
      conjugation: 'ik pull, jij pullt, hij pullt, wij pullen',
      sentence: 'Vergeet niet te pullen voor je begint.',
    },
    {
      number: 61,
      english: 'To estimate',
      dutch: 'Inschatten',
      conjugation: 'ik schat in, jij schat in, hij schat in, wij schatten in',
      sentence: 'Hoe schat jij de tijd in voor dit ticket?',
    },
    {
      number: 62,
      english: 'To refactor',
      dutch: 'Refactoren',
      conjugation: 'ik refactor, jij refactort, hij refactort, wij refactoren',
      sentence: 'We moeten deze code refactoren.',
    },
    {
      number: 63,
      english: 'To investigate',
      dutch: 'Onderzoeken',
      conjugation: 'ik onderzoek, jij onderzoekt, hij onderzoekt, wij onderzoeken',
      sentence: 'Ik ga de bug onderzoeken.',
    },
    {
      number: 64,
      english: 'To improve',
      dutch: 'Verbeteren',
      conjugation: 'ik verbeter, jij verbetert, hij verbetert, wij verbeteren',
      sentence: 'We kunnen de performance verbeteren.',
    },
    {
      number: 65,
      english: 'To add',
      dutch: 'Toevoegen',
      conjugation: 'ik voeg toe, jij voegt toe, hij voegt toe, wij voegen toe',
      sentence: 'Ik voeg een nieuwe endpoint toe.',
    },
    {
      number: 66,
      english: 'To remove',
      dutch: 'Verwijderen',
      conjugation: 'ik verwijder, jij verwijdert, hij verwijdert, wij verwijderen',
      sentence: 'We moeten de oude code verwijderen.',
    },
    {
      number: 67,
      english: 'To approve',
      dutch: 'Goedkeuren',
      conjugation: 'ik keur goed, jij keurt goed, hij keurt goed, wij keuren goed',
      sentence: 'Kun je mijn PR goedkeuren?',
    },
    {
      number: 68,
      english: 'To reject',
      dutch: 'Afwijzen',
      conjugation: 'ik wijs af, jij wijst af, hij wijst af, wij wijzen af',
      sentence: 'De PR werd afgewezen vanwege een fout.',
    },
    {
      number: 69,
      english: 'To share',
      dutch: 'Delen',
      conjugation: 'ik deel, jij deelt, hij deelt, wij delen',
      sentence: 'Kun je je scherm delen?',
    },
    {
      number: 70,
      english: 'To show',
      dutch: 'Laten zien',
      conjugation: 'ik laat zien, jij laat zien, hij laat zien, wij laten zien',
      sentence: 'Ik laat de nieuwe feature zien tijdens de demo.',
    },
    {
      number: 71,
      english: 'To present',
      dutch: 'Presenteren',
      conjugation: 'ik presenteer, jij presenteert, hij presenteert, wij presenteren',
      sentence: 'Ik ga de resultaten presenteren.',
    },
    {
      number: 72,
      english: 'To attend',
      dutch: 'Bijwonen',
      conjugation: 'ik woon bij, jij woont bij, hij woont bij, wij wonen bij',
      sentence: 'Ik woon de standup bij.',
    },
    {
      number: 73,
      english: 'To schedule',
      dutch: 'Inplannen',
      conjugation: 'ik plan in, jij plant in, hij plant in, wij plannen in',
      sentence: 'Kun je de meeting inplannen?',
    },
    {
      number: 74,
      english: 'To cancel',
      dutch: 'Annuleren',
      conjugation: 'ik annuleer, jij annuleert, hij annuleert, wij annuleren',
      sentence: 'De meeting is geannuleerd.',
    },
    {
      number: 75,
      english: 'To postpone',
      dutch: 'Uitstellen',
      conjugation: 'ik stel uit, jij stelt uit, hij stelt uit, wij stellen uit',
      sentence: 'We moeten de deadline uitstellen.',
    },
    {
      number: 76,
      english: 'To report',
      dutch: 'Rapporteren',
      conjugation: 'ik rapporteer, jij rapporteert, hij rapporteert, wij rapporteren',
      sentence: 'Ik ga de voortgang rapporteren.',
    },
    {
      number: 77,
      english: 'To block',
      dutch: 'Blokkeren',
      conjugation: 'ik blokkeer, jij blokkeert, hij blokkeert, wij blokkeren',
      sentence: 'Dit ticket blokkeert mijn werk.',
    },
    {
      number: 78,
      english: 'To depend on',
      dutch: 'Afhangen van',
      conjugation: 'het hangt af van',
      sentence: 'Dit hangt af van de backend implementatie.',
    },
    {
      number: 79,
      english: 'To integrate',
      dutch: 'Integreren',
      conjugation: 'ik integreer, jij integreert, hij integreert, wij integreren',
      sentence: 'We moeten de API integreren.',
    },
    {
      number: 80,
      english: 'To automate',
      dutch: 'Automatiseren',
      conjugation: 'ik automatiseer, jij automatiseert, hij automatiseert, wij automatiseren',
      sentence: 'We willen het testproces automatiseren.',
    },
    {
      number: 81,
      english: 'To monitor',
      dutch: 'Monitoren',
      conjugation: 'ik monitor, jij monitort, hij monitort, wij monitoren',
      sentence: 'We monitoren de applicatie in productie.',
    },
    {
      number: 82,
      english: 'To log',
      dutch: 'Loggen',
      conjugation: 'ik log, jij logt, hij logt, wij loggen',
      sentence: 'De applicatie logt alle fouten.',
    },
    {
      number: 83,
      english: 'To debug',
      dutch: 'Debuggen',
      conjugation: 'ik debug, jij debugt, hij debugt, wij debuggen',
      sentence: 'Ik ben aan het debuggen.',
    },
    {
      number: 84,
      english: 'To optimize',
      dutch: 'Optimaliseren',
      conjugation: 'ik optimaliseer, jij optimaliseert, hij optimaliseert, wij optimaliseren',
      sentence: 'We moeten de query optimaliseren.',
    },
    {
      number: 85,
      english: 'To migrate',
      dutch: 'Migreren',
      conjugation: 'ik migreer, jij migreert, hij migreert, wij migreren',
      sentence: 'We migreren de database naar de cloud.',
    },
    {
      number: 86,
      english: 'To store',
      dutch: 'Opslaan',
      conjugation: 'ik sla op, jij slaat op, hij slaat op, wij slaan op',
      sentence: 'De gegevens worden opgeslagen in de database.',
    },
    {
      number: 87,
      english: 'To load',
      dutch: 'Laden',
      conjugation: 'ik laad, jij laadt, hij laadt, wij laden',
      sentence: 'De pagina laadt te langzaam.',
    },
    {
      number: 88,
      english: 'To upload',
      dutch: 'Uploaden',
      conjugation: 'ik upload, jij uploadt, hij uploadt, wij uploaden',
      sentence: 'Ik upload het bestand naar de server.',
    },
    {
      number: 89,
      english: 'To download',
      dutch: 'Downloaden',
      conjugation: 'ik download, jij downloadt, hij downloadt, wij downloaden',
      sentence: 'Kun je het bestand downloaden?',
    },
    {
      number: 90,
      english: 'To access',
      dutch: 'Toegang hebben',
      conjugation: 'ik heb toegang, jij hebt toegang',
      sentence: 'Ik heb geen toegang tot de server.',
    },
    {
      number: 91,
      english: 'To learn',
      dutch: 'Leren',
      conjugation: 'ik leer, jij leert, hij leert, wij leren',
      sentence: 'Ik leer de codebase kennen.',
    },
    {
      number: 92,
      english: 'To follow',
      dutch: 'Volgen',
      conjugation: 'ik volg, jij volgt, hij volgt, wij volgen',
      sentence: 'Ik volg de onboarding procedure.',
    },
    {
      number: 93,
      english: 'To agree',
      dutch: 'Akkoord gaan',
      conjugation: 'ik ga akkoord, jij gaat akkoord',
      sentence: 'Ik ga akkoord met het voorstel.',
    },
    {
      number: 94,
      english: 'To disagree',
      dutch: 'Het er niet mee eens zijn',
      conjugation: 'ik ben het er niet mee eens',
      sentence: 'Ik ben het er niet mee eens — ik denk dat er een betere aanpak is.',
    },
    {
      number: 95,
      english: 'To suggest',
      dutch: 'Voorstellen',
      conjugation: 'ik stel voor, jij stelt voor, hij stelt voor, wij stellen voor',
      sentence: 'Ik stel voor om dit anders aan te pakken.',
    },
    {
      number: 96,
      english: 'To respond',
      dutch: 'Reageren',
      conjugation: 'ik reageer, jij reageert, hij reageert, wij reageren',
      sentence: 'Ik reageer zo snel mogelijk op je vraag.',
    },
    {
      number: 97,
      english: 'To handle',
      dutch: 'Afhandelen',
      conjugation: 'ik handel af, jij handelt af, hij handelt af, wij handelen af',
      sentence: 'Ik handel de foutmelding af.',
    },
    {
      number: 98,
      english: 'To repeat',
      dutch: 'Herhalen',
      conjugation: 'ik herhaal, jij herhaalt, hij herhaalt, wij herhalen',
      sentence: 'Kun je dat herhalen? Ik verstond je niet.',
    },
    {
      number: 99,
      english: 'To continue',
      dutch: 'Doorgaan',
      conjugation: 'ik ga door, jij gaat door, hij gaat door, wij gaan door',
      sentence: 'Laten we doorgaan met de volgende taak.',
    },
    {
      number: 100,
      english: 'To succeed',
      dutch: 'Slagen',
      conjugation: 'ik slaag, jij slaagt, hij slaagt, wij slagen',
      sentence: 'Ik wil slagen in mijn nieuwe rol.',
    },
  ];

  get filteredVerbs(): DutchVerb[] {
    if (!this.searchQuery.trim()) return this.verbs;
    const q = this.searchQuery.toLowerCase();
    return this.verbs.filter(
      (v) =>
        v.english.toLowerCase().includes(q) ||
        v.dutch.toLowerCase().includes(q) ||
        v.conjugation.toLowerCase().includes(q) ||
        v.sentence.toLowerCase().includes(q)
    );
  }
}
